ifdef CONFIG_HTC_DEBUG
obj-$(CONFIG_HTC_DEBUG) += htc_debug_tools.o
obj-$(CONFIG_HTC_REBOOT_BLOCK) += htc_reboot_block.o
obj-$(CONFIG_HTC_HELPER_FUNCTIONS) += helper_funcs.o
obj-$(CONFIG_HTC_NC_GPIO_PIN_SETTING)  += htc_nc_setting.o
obj-$(CONFIG_HTC_DEBUG_RESTART_TIMER) += htc_restart_timer_notifier.o
endif
